root: false
language: node_js
os: ubuntu
dist: 'focal'
node_js:
  - '12.18.3'
addons: 
  ssh_known_hosts: github.com:22
before_install:
  - openssl aes-256-cbc -K $encrypted_b47cedfbbf03_key -iv $encrypted_b47cedfbbf03_iv -in github.key.enc -out github.key -d
  - chmod 600 github.key
  - npm i yarn -g
install:
  - yarn
  - yarn build
after_script:
  - chmod +x ./ci-deploy.sh
  - bash ./ci-deploy.sh
